---
title: "Latin American Politics"
author: "Danilo Freire"
date: "April 2021"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: pdflatex
    template: ~/Documents/github/danilofreire.github.io/syllabi/template.tex
  word_document: default
email: danilofreire@gmail.com
fontfamily: libertine
fontsize: 12pt
geometry: margin=1in
header-includes: \linespread{1.05}
office: TBA
officehours: TBA
classroom: TBA
classhours: TBA
web: danilofreire.github.io
---

# Course Description

The objective of this class is to provide a broad overview of the main questions on Latin America's political economy. Specifically, we will address some features of Latin American regimes, such as inequality, violence, economic development, and authoritarianism. We will also analyse how political systems foster or hinder economic growth, and the ways in which corruption, clientelism, and crime affect the welfare of Latin American citizens. Finally, we will discuss the rise of left-wing parties in the 2000s in the continent as well as its recent right turn.

# Course Information

It is very important that you read the assigned readings before class. Students are encouraged to engage in critical discussions and are most welcome to express their views openly and freely. I would suggest you to bring some notes to the class so that we can discuss together the topics you find most interesting. Although some of the readings use formal models or statistical methods to develop their arguments, no previous knowledge of game theory or quantitative methods is required. Feel free to skip the technical parts if they are too challenging and focus on the main ideas of the readings.

All information about the course will be available at [http://danilofreire.github.io](http://danilofreire.github.io). The syllabus will be updated periodically according to the progress of the class. Please remember to visit the website regularly.

# Office Hours

I am very flexible when it comes to office hours, but it is easier to contact me via email. Feel free to send me a message any time at [danilofreire@gmail.com](mailto:danilofreire@gmail). I will reply in a few hours. You can also meet me in the afternoon at my office. If possible, please send me an email before coming to my office just to make sure two students will not book the same time slot.

# Community Standards

I am committed to full inclusion of all students. Please inform me early in the term if you have a disability or other conditions that might require accommodations or modification of any of these course procedures. You may speak with me after class or during office hours. Students in need of short-term academic advice or support can contact one of the deans in the Dean of the College office.

# English Language Learners

The university welcomes students from around the country and the world, and the unique perspectives international and multilingual students bring enrich the campus community. To empower multilingual learners, an array of support is available including language and culture workshops and individual appointments. No student will be penalised for their command of the English language.

# Academic Integrity

Students will write three review reports and a longer essay for this course. All writing should be your own work, and I take plagiarism very seriously. I am happy to provide any help you may require with your lessons as long as you are committed to the course. It is also important to cite other people's work whenever necessary, and if in doubt, mention your sources. 

# Special Needs

If you have any special needs, please contact me. I'm happy to make necessary arrangements so you can follow this course.

# Requirements and Grading 

**Participation: 15%.**  Students should be active participants in the course. Feel free to ask any question you may have, help others if you know how, and make suggestions or comments you believe are interesting. I hope we create a friendly, open environment for learning and students are the most important part of it.

**Three Review Reports: 45%.**  The reviews should be 3-5 pages long. Imagine you are a reviewer for a good academic journal and think of how you could help the author improve the article. Are the arguments well-developed in the text? Is the research design plausible? What further examples could the author include to strenghten his/her arguments? Try to provide as much constructive criticism as possible. You don't need to summarise the paper, just critically engage with it. The essays are due at the beginning of the class and late assignments will not be eligible for an A. Each report will account for 15% of your grade.

**Final Project: 40%.** In the final project, students will have the opportunity to write a longer essay about a topic that interests them. The essay should be related to the readings of the course, but you are particularly encouraged to explore new ideas and use new data to test their hypotheses. Students can work in groups of up to three people as most academic research is currently done collaboratively. By the second week of the course, students should submit a one-page summary of their future essay. The instructor and two colleagues will review the paper proposal and give the authors constructive feedback. Students will then write a full draft during the term. In the last week of the course, students will present their findings to the class and receive feedback from their colleagues. The final paper is due one week after that. 

# Materials

The book required for this class is:

* Skidmore T. E., Smith, P. E., and Green, J. N. (2014). [Modern Latin America](https://smile.amazon.com/Modern-Latin-America-Peter-Smith/dp/0190674652/ref=sr_1_1?keywords=Modern+Latin+America&qid=1569732045&sr=8-1). New York, NY: Oxford University Press, 8\textsuperscript{th} edition.

# Schedule

## Week 1: Introduction and Course Overview 

There are no readings assigned for this class. I will discuss the papers and the main topics that we will study during the class. 

## Week 2: Historical Overview

### Required Readings

* Skidmore T. E., Smith, P. E., and Green, J. N. (2014). [Modern Latin America](https://smile.amazon.com/Modern-Latin-America-Peter-Smith/dp/0190674652/ref=sr_1_1?keywords=Modern+Latin+America&qid=1569732045&sr=8-1), New York, NY: Oxford University Press. Chapters 1-2.
* Hartlyn, J. and Valenzuela, A. (1994). [Democracy in Latin America since 1930](https://www.cambridge.org/core/books/latin-america/democracy-in-latin-america-since-1930/FB26AE907EDE6450B2769105CF3926DD). In: Bethell, L. (ed.), _Latin America since 1930: Economy, Society and Politics_. New York, NY: Cambridge University Press.
* Bertola, L. and Ocampo, J. A. (2012). [The Economic Development of Latin America since Independence](https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199662135.001.0001/acprof-9780199662135-chapter-1). New York, NY: Oxford University Press. Chapter 1.

### Recommended Readings

* Drake, P. W. (2009). [Between Tyranny and Anarchy: A History of Democracy in Latin America, 1800-2006](https://www.sup.org/books/title/?id=16581). Stanford, CA: Stanford University Press. Chapter 2.
* Smith, P. H. (2011). [Democracy in Latin America: Political Change in Comparative Perspective](https://smile.amazon.com/Democracy-Latin-America-Comparative-Perspective/dp/0195157591). New York, NY: Oxford University Press. Chapter 1.
* Bulmer-Thomas, V. (2004). [The Economic History of Latin America since Independence](https://www.cambridge.org/core/books/economic-history-of-latin-america-since-independence/latin-american-economic-development/B154DF3B26F6049B12F1C6BC66126D2B). New York, NY: Cambridge University Press. Chapter 1.

## Week 3: State-Building and Long-Run Development

### Required Readings

* Acemoglu, D. and Robinson, J. (2013). [Why Nations Fail? The Origins of Power, Prosperity, and Poverty](http://www.whynationsfail.com). New York, NY: Crown Business. Preface, chapters 1-3.
* Acemoglu, D., Johnson, S., and Robinson, J. (2005), [Institutions as a Fundamental Cause of Long Run Growth](http://economics.mit.edu/files/4469). In: Aghion, P. and Durlauf, S. (eds.), _Handbook of Economic Growth_, Vol. 1A. Amsterdam: North Holland.
* Sokoloff, K. L. and Engerman, S. L. (2000). [Institutions, Factor Endowments, and Paths of Development in the New World](https://www.aeaweb.org/articles?id=10.1257/jep.14.3.217). _Journal of Economic Perspectives_, 14(3), 217-232. 

## Week 4: Dependency and Modernisation 

### Required Readings

* Acemoglu, D., Johnson, S., Robinson, J., and Yared, P. (2008). [Income and Democracy](https://www.aeaweb.org/articles?id=10.1257/aer.98.3.808). _American Economic Review_, 98(3): 808-842.
* Acemoglu, D., Johnson, S., Robinson, J., and Yared, P. (2009). [Reevaluating the Modernization Hypothesis](https://www.sciencedirect.com/science/article/abs/pii/S0304393209001299). _Journal of Monetary Economics_, 56(8),1043–1058.
* Heller, P., Rueschemeyer, D., and Snyder, R. (2009). [Dependency and Development in a Globalized World: Looking Back and Forward](https://link.springer.com/article/10.1007/s12116-009-9055-y). _Studies in Comparative International Development_, 44(4), 287-295.

### Recommended Readings

* Frank, A. (1986). [The Development of Underdevelopment](https://pdfs.semanticscholar.org/846c/1a98dc6b5aec1463fb570ab7037a2e95e126.pdf). In: Klaren, P. and Bossert, T. (eds.), _Promise of Development_, Boulder, CO: Westview Press.
* Cardoso, F. H. and Faletto, E. (1979). [Dependency and Development in Latin America](https://smile.amazon.com/Dependency-Development-America-Fernando-Henrique/dp/0520035275). Berkeley, CA: University of California Press.
* Valenzuela, J. S. and Valenzuela, A. (1978). [Modernization and Dependency: Alternative Perspectives in the Study of Latin American Underdevelopment](https://www.jstor.org/stable/421571?seq=1#metadata_info_tab_contents). _Comparative Politics_, 10(4), 535-557.

## Week 5: Colonial Legacies

### Required Readings

* Acemoglu, D., Johnson, S., and Robinson, J. (2002). [Reversal of Fortune: Geography and Institutions in the Making of the Modern World Income Distribution](https://academic.oup.com/qje/article-abstract/117/4/1231/1875948?redirectedFrom=fulltext). _The Quarterly Journal of Economics_, 117(4), 1231-1294.
* Acemoglu, D., Johnson, S., and Robinson, J. (2001). [The Colonial Origins of Comparative Development: An Empirical Investigation](https://www.aeaweb.org/articles?id=10.1257/aer.91.5.1369). _American Economic Review_, 91(5), 1369-1401.
* Coatsworth, J. H. (2008). [Inequality, Institutions, and Economic Growth in Latin America](https://www.jstor.org/stable/40056706#metadata_info_tab_contents). _Journal of Latin American Studies_, 40(3), 545-569.

### Recommended Readings

* Coatsworth, J. H. (2005). [Structures, Endowments, and Institutions in the Economic History of Latin America](https://www.jstor.org/stable/3662825?seq=1#metadata_info_tab_contents). _Latin American Research Review_, 40(3), 126-144.
* Dell, M. (2010). [The Persistent Effect of Peru’s Mining Mita](https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA8121), _Econometrica_, 78(6), 1863-1903.

## Week 6: Emerging Markets and States

### Required Readings

* Mazzuca, S. and Robinson, J. (2009). [Political Conflict and Power Sharing in the Origins of Modern Colombia](https://scholar.harvard.edu/files/jrobinson/files/jr_colombia.pdf). _Hispanic American Historical Review_, 89(2), 285-321.
* Safford, F. (1992). [The Problem of Political Order in Early Republican Spanish America](https://www.jstor.org/stable/156947?seq=1#metadata_info_tab_contents). _Journal of Latin American Studies_, 24: 83-97
* Centeno, M. (1997). [Blood and Debt: War and Taxation in Nineteenth-Century Latin America](https://www.jstor.org/stable/10.1086/231127?seq=1#metadata_info_tab_contents). _The American Journal of Sociology_, 102(6), 1565-1605.

### Recommended Readings

* Mahoney, J. (2001). [Radical, Reformist and Aborted Liberalism: Origins of National Regimes in Central America](https://www.jstor.org/stable/3653684?seq=1#metadata_info_tab_contents). _Journal of Latin American Studies_, 33(2), 221-256.
* Glade, W. (1986), [Latin America and the International Economy, 1870–1914](https://www.cambridge.org/core/books/cambridge-history-of-latin-america/latin-america-and-the-international-economy-18701914/A3330A94EF49D8381F2BDDE5389EF661). In: Bethell, L. (ed.), _Latin America since 1930: Economy, Society and Politics_, New York, NY: Cambridge University Press.
* Katz, F. (1991), [The Liberal Republic and the Porfiriato, 1867-1910](https://www.cambridge.org/core/books/mexico-since-independence/liberal-republic-and-the-porfiriato-18671910/BB2D367300B9AED89C61B2DC2F50B2CE). In: Bethell, L. (ed.). _Mexico Since Independence_, New York, NY: Cambridge University Press.

## Week 7: Theories on Democracy and Dictatorship 

### Required Readings

* Acemoglu, D. and Robinson, J. (2006). [Economic Origins of Dictatorship and Democracy](https://smile.amazon.com/Economic-Origins-Dictatorship-Democracy-Acemoglu/dp/0521671426). New York, NY: Cambridge University Press. Chapters 1-3.
* Lizzeri, A. and Persico, N. (2004). [Why did the Elites Extend the Suffrage? Democracy and the Scope of Government, with an Application to Britain’s 'Age of Reform'](http://qje.oxfordjournals.org/content/119/2/707.short). _Quarterly Journal of Economics_, 119(2), 707-765.
* Llavador, H. and Oxoby, R. (2005). [Partisan Competition, Growth, and the Franchise](https://academic.oup.com/qje/article-abstract/120/3/1155/1841475). _Quarterly Journal of Economics_, 120(3), 1155-1189.

### Recommended Readings

* Przeworski, A. (1991). [Democracy and the Market: Political and Economic Reforms in Eastern Europe and Latin America](https://smile.amazon.com/Democracy-Market-Political-Economic-Rationality/dp/052142335X). New York, NY: Cambridge University Press.

## Week 8: The Rise of Populism and Incorporation of the Masses 

### Required Readings

* Skidmore T. E., Smith, P. E., and Green, J. N. (2014). [Modern Latin America](https://smile.amazon.com/Modern-Latin-America-Peter-Smith/dp/0190674652/ref=sr_1_1?keywords=Modern+Latin+America&qid=1569732045&sr=8-1), New York, NY: Oxford University Press. Chapter 3.
* Hirschman, A. (1968). [The Political Economy of Import-Substituting Industrialization in Latin America](https://www.jstor.org/stable/1882243?seq=1#metadata_info_tab_contents). _Quarterly Journal of Economics_, 82(1), 1-32.
* Chacon, M., Robinson, J., and Torvik, R. (2011). [When is Democracy an Equilibrium? Theory and Evidence from Colombia’s La Violencia”](https://www.jstor.org/stable/23049891?seq=1#metadata_info_tab_contents). _Journal of Conflict Resolution_, 55(3), 366-396.

### Recommended Readings

* Baland, J. and Robinson, J. (2008). [Land and Power: Theory and Evidence from Chile](https://scholar.harvard.edu/files/jrobinson/files/jr_landandpower.pdf). _American Economic Review_, 98(5), 1737-65.
* Bushnell, D. (1993). [The Making of Modern Colombia: A Nation in Spite of Itself](https://smile.amazon.com/Making-Modern-Colombia-Nation-Itself/dp/0520082893). Berkeley, CA: University of California Press, Chapters 8-9.
* Collier, R. and Collier, D. (2002). [Shaping the Political Arena: Critical Junctures, the Labor Movement, and Regime Dynamics in Latin America](https://smile.amazon.com/Shaping-Political-Institute-Democracy-Development/dp/0268017727), Notre Dame, IN: Notre Dame University Press.

## Week 9: Insurgency and Revolutions

### Required Readings

* Wood, E. J. (2001). [An Insurgent Path to Democracy: Popular Mobilization, Economic Interests and Regime Transition in South Africa and El Salvador](https://journals.sagepub.com/doi/10.1177/0010414001034008002). _Comparative Political Studies_, 34(8), 862-888.
* Eckstein, S. (1986). [The Impact of the Cuban Revolution: A Comparative Perspective](https://www.jstor.org/stable/178861?seq=1#metadata_info_tab_contents), _Comparative Studies in Society and History_, 28(3), 502-534.
* Safford, F. and Palacios, M. (2002). [Colombia: Fragmented Land, Divided Society](https://smile.amazon.com/Colombia-Fragmented-Divided-American-Histories/dp/019504617X). New York, NY: Oxford University Press. Chapter 14.

### Recommended Readings

* Paige, J. (1998). [Coffee and Power: Revolution and the Rise of Democracy in Central America](https://smile.amazon.com/Coffee-Power-Revolution-Democracy-Central/dp/0674136497). Cambridge, MA: Harvard University Press.
* Leon, J. (2008). [Country of Bullets: Chronicles of War](https://smile.amazon.com/Country-Bullets-Chronicles-Juanita-Leon-ebook/dp/B005R33UR0/ref=sr_1_1?keywords=Country+of+Bullets%3A+Chronicles+of+War&qid=1569783310&s=books&sr=1-1). Albuquerque, NM: University of New Mexico Press.

## Week 10: Breakdown of Democracy and Rise of Authoritarianism

### Required Readings

* Cohen, Y. (1987). [Democracy from Above: The Political Origins of Military Dictatorship in Brazil](https://www.jstor.org/stable/2010193?seq=1#metadata_info_tab_contents). _World Politics_, 40(1), 30-54.
* Kornbluh, P. (2003). [The Pinochet File: A Declassified Dossier on Atrocity and Accountability](https://smile.amazon.com/Pinochet-File-Declassified-Atrocity-Accountability-ebook/dp/B00EXCAJAM). New York: The New Press. Chapters 1-2.
* Schamis, H. E. (1991). [Reconceptualizing Latin American Authoritarianism in the 1970s: From Bureaucratic Authoritarianism to Neoconservatism](https://www.jstor.org/stable/pdf/422361.pdf). _Comparative Politics_, 23(2), 201-216. 

### Recommended Readings

* Linz, J. and Stepan, A. (eds.) (1978). [The Breakdown of Democratic Regimes: Latin America](https://smile.amazon.com/Breakdown-Democratic-Regimes-Latin-America/dp/0801820235). Baltimore, MD: Johns Hopkins University Press.
* Stepan, A. (ed.) (1973). [Authoritarian Brazil](https://smile.amazon.com/Authoritarian-Brazil-Origins-Policies-Future/dp/0300016220/ref=sr_1_1?keywords=Authoritarian+Brazil+stepan&qid=1569783513&s=books&sr=1-1). New Haven, CT: Yale University Press.
* Valenzuela, A. (1978). [The Breakdown of Democratic Regimes: Chile](https://smile.amazon.com/Breakdown-Democratic-Regimes-Chile/dp/0801820103/ref=sr_1_1?keywords=The+Breakdown+of+Democratic+Regimes%3A+Chile&qid=1569783536&s=books&sr=1-1). Baltimore, MD: Johns Hopkins University Press.

## Week 11: Democratisation 

### Required Readings

* Karl, T. (1990). [Dilemmas of Democratization in Latin America](https://www.jstor.org/stable/422302?seq=1#metadata_info_tab_contents). _Comparative Politics_, 3(1), 1-21.
* O’Donnell, G. (1999). [Notes for the Study of Processes of Political Democratization in the Wake of the Bureaucratic-Authoritarian State](https://scholar.harvard.edu/files/levitsky/files/counterpoints_odonell.pdf). In: O'Donnell, G. _Counterpoints_, Notre Dame, IN: University of Notre Dame Press.
* Haggard, S. and Kaufman, R. (1997). [The Political Economy of Democratic Transitions](https://www.jstor.org/stable/422121?seq=1#metadata_info_tab_contents). _Comparative Politics_ 29(3), 285-303. 

### Recommended Readings

* Hagopian, F. (1990). [Democracy by Undemocratic Means: Elites, Political Pacts, and Regime Transition in Brazil](https://journals.sagepub.com/doi/abs/10.1177/0010414090023002001). _Comparative Political Studies_, 23(2), 147-169.
* Londregan, J. (2000). [Legislative Institutions and Ideology in Chile](https://www.cambridge.org/core/books/legislative-institutions-and-ideology-in-chile/2B7486276138A9949FB9F2F978DB3D98). New York, NY: Cambridge University Press.
* Hagopian, F. and Mainwaring, S. (eds.) (2005). [The Third Wave of Democratization in Latin America: Advances and Setbacks](https://www.cambridge.org/core/books/third-wave-of-democratization-in-latin-america/C215ABA34B16065EF75A1717CDD1001E). New York, NY: Cambridge University Press.

## Week 12: Macroeconomic Crisis and Economic Reforms

### Required Readings

* Acemoglu, D., Johnson, S., Robinson, J., and  Thaicharoen, Y. (2003). [Institutional Causes, Macroeconomic Symptoms: Volatility, Crises and Growth](https://www.sciencedirect.com/science/article/abs/pii/S0304393202002088). _Journal of Monetary Economics_, 50(1), 49-123.
* Dornbusch, R. and Edwards, S. (1990). [Macroeconomic Populism](https://www.sciencedirect.com/science/article/abs/pii/030438789090038D). _Journal of Development Economics_, 32(2), 247-275. 
* Acemoglu, D., Johnson, S., Querubín, P., and Robinson, J. (2008). [When Does Policy Reform Work? The Case of Central Bank Independence”](https://www.brookings.edu/wp-content/uploads/2008/03/2008a_bpea_acemoglu.pdf). In: Brookings Papers on Economic Activity, Spring, 351-417.

### Recommended Readings

* Pastor, M. (1991). [Bolivia: Hyperinflation, Stabilization, and Beyond](https://www.tandfonline.com/doi/abs/10.1080/00220389108422193?journalCode=fjds20). _Journal of Development Studies_, 27(2), 211-233.
* Roxborough, I. (1992). [Inflation and Social Pacts in Brazil and Mexico](https://www.cambridge.org/core/journals/journal-of-latin-american-studies/article/inflation-and-social-pacts-in-brazil-and-mexico/5F181507128753E0679A4FF769DF0383). _Journal of Latin American Studies_, 24(3), 639-664.
* Green, D. (2003). [Silent Revolution: The Rise And Crisis Of Market Economics In Latin America](https://smile.amazon.com/Silent-Revolution-Crisis-Economics-America/dp/1583670912). New York, NY: Monthly Review Press.

\newpage 

## Week 13: Dysfunctional and Weak States

### Required Readings

* O’Donnell, G. (1993). [On the State, Democratization and some Conceptual Problems: A Latin American View with Glances at some Postcommunist Countries](https://www.sciencedirect.com/science/article/abs/pii/0305750X9390048E). _World Development_, 21(8), 1355-1369.
* Mainwaring, S. (2006). [The Crisis of Representation in the Andes](https://www.journalofdemocracy.org/articles/the-crisis-of-representation-in-the-andes/). _Journal of Democracy_, 17(3), 13-27.
* Acemoglu, D., Robinson, J., and Santos, R. (2013). [The  Monopoly of Violence: Evidence from Colombia](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1542-4774.2012.01099.x). _Journal of the European Economic Association_, 11, 5-44.

### Recommended Readings

* Dell, M. (2011). [Trafficking Networks and the Mexican Drug War](https://www.aeaweb.org/articles?id=10.1257/aer.20121637). _American Economic Review_, 105(6), 1738-1779.
* Robinson, J. (2013). [Colombia: Another 100 Years of Solitude?](https://scholar.harvard.edu/files/jrobinson/files/robinson-current_history.pdf). _Current History_, 112(751), 43-48.
* Gibson, E. (2005). [Boundary Control: Subnational Authoritarianism in Democratic Countries](https://www.cambridge.org/core/journals/world-politics/article/boundary-control-subnational-authoritarianism-in-democratic-countries/52ED7708A69F4F875C4BBC9B9EE913B6). _World Politics_, 58(1), 101-132.
* Vom Hau, M. (2008). [State Infrastructural Power and Nationalism: Comparative Lessons from Mexico and Argentina](https://link.springer.com/article/10.1007/s12116-008-9024-x). _Studies in International Comparative Development_, 43(3), 334-354.

## Week 14: The Rise of Left-Wing Parties in Latin America 

### Required Readings

* Pickup, M. (2019). [The Political Economy of the New Left](https://journals.sagepub.com/doi/full/10.1177/0094582X18803878). _Latin American Perspectives_, 46(1), 23-45.
* Weyland, K. (2009). [The Rise of Latin America’s Two Lefts: Insights from Rentier State Theory](https://www.jstor.org/stable/40599207?seq=1#metadata_info_tab_contents). _Comparative Politics_, 41(2): 145-164.
* Mazzuca, S. (2013). [The Rise of Rentier Populism](https://www.journalofdemocracy.org/articles/lessons-from-latin-america-the-rise-of-rentier-populism/). _Journal of Democracy_, 24(2), 108-122.
* Samuels, D. (2004). [From Socialism to Social Democracy: Party Organization and the Transformation of the Workers' Party in Brazil](https://journals.sagepub.com/doi/10.1177/0010414004268856). _Comparative Political Studies_, 37(9), 999-1024.

### Recommended Readings

* Weyland, K. (2001). [Clarifying a Contested Concept: Populism in the Study of Latin American Politics](https://www.jstor.org/stable/pdf/422412.pdf). _Comparative Politics_, 34(1): 1-22.
* Levitsky, S. and Roberts, K. (Eds.) (2011) [The Resurgence of the Latin American Left](https://muse.jhu.edu/book/1866), Baltimore, MD: Johns Hopkins University Press.
* Edwards, S. (2010). [Left Behind: Latin America and the False Premise of Populism](https://smile.amazon.com/Left-Behind-America-Promise-Populism/dp/022600466X). Chicago, IL: University of Chicago Press.

\newpage

## Week 15: A New Shift to the Right? 

### Required Readings

- Grier, K. and Maynard, N. (2016). [The Economic Consequences of Hugo Chavez: A Synthetic Control Analysis](https://www.sciencedirect.com/science/article/pii/S0167268116000020). _Journal of Economic Behavior & Organization_, 125, 1-21.
* Hunter, W. and Power, T. J. (2019). [Bolsonaro and Brazil's Illiberal Backlash](https://www.journalofdemocracy.org/articles/bolsonaro-and-brazils-illiberal-backlash/). _Journal of Democracy_, 30(1), 68-82.
* Murillo, M. V. and Levitsky, S. (2019). [Partisan Realignment in Argentina](https://smile.amazon.com/Campaigns-Voters-Developing-Democracies-Comparative/dp/0472131281/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1569785010&sr=1-1). In: Lupu, N., Oliveros, V., and Schiumerini, L. _Campaigns and Voters in Developing Democracies: Argentina in Comparative Perspective_, Ann Arbor, MI: University of Michigan Press.

